{
 class node {
  constructor(valor) {
    this.valor = valor
    this.siguiente = null
  }

  push(valor) {            
    var temp = new node(valor)
    temp.siguiente = head
    head = temp
  }
  
  }
  let head = null;
 }

s = n:e* { 
		for (var i = 0; i < n.length; i+=1) {
  if (head!=null) head.push(n[i]);
  else head = new node(n[i]);
}
return head;
      }

e = n:num sep { return n; }

num = n:[0-9]+ { return parseInt(n,10); }

sep = "\n"