s = output:e {
        integer :: res
        res = output
    }

e = left:t "+" right:e {
        integer :: res
        res = left + right
    }
    / left:t "-" right:e {
        integer :: res
        res = left - right
    }
    / t

t = left:f "*" right:t {
        integer :: res
        res = left * right
    }
    / left:f "/" right:t {
        integer :: res
        res = left / right
    }
    / f 

f = "(" exp:e ")" {
        integer :: res
        res = exp
    }
    / _ num:[0-9]+ _ {
        integer :: res
        read(num, *) res
    }

_ = [ \t\n\r]*